### PR TITLE
Use lowercase DateTime.monday etc. constants

### PR DESCRIPTION
**Pull request by SteveAlexander**
see https://github.com/dnfield/dart_calendar/issues/3

### CODE REVIEW

**Comment by dnfield** [comment]
Can you update pubspec to specify the appropriate sdk version constraint for this?

**Comment by SteveAlexander** [comment]
Sure, done

**Comment by dnfield** [comment]
Not sure the commit has made it through...

**Comment by SteveAlexander** [comment]
sorry — I'd updated a different branch and confused myself. I made a new pull request with all changes so far:

https://github.com/dnfield/dart_calendar/pull/5

**Pull request closed without merging**
